name: Glog.AI Scan

on: 
  workflow_dispatch:

jobs:
  glog-scan-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
  
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
  
      - uses: gradle/actions/setup-gradle@v3
  
      - run: gradle build


      - name: Checkout glog-action repository
        uses: actions/checkout@v4
        with:
          repository: glogai/glog-action
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/glog-action
          ref: main

      - name: Run Glog.AI from private repo
        uses: ./.github/glog-action
        with:
          lang: 'kotlin'
          debug: 'false'
          upload: 'true'
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
